/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.terra_snack.view;

/**
 *
 * @author ADMIN
 */
import com.mycompany.terra_snack.dao.EventBazarDAO;
import com.mycompany.terra_snack.model.EventBazar;
 
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
 
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
 
/**
 *
 * @author ADMIN
 */
public class EventBazarFormFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EventBazarFormFrame.class.getName());
 
    // =========================================================================
    // FIELD TAMBAHAN (aman di luar blok GEN-BEGIN/GEN-END, tidak akan
    // ditimpa NetBeans walau form ini dibuka lagi di Design view)
    // =========================================================================
 
    /** DAO untuk akses tabel event_bazar di database */
    private final EventBazarDAO eventBazarDAO = new EventBazarDAO();
 
    /** Model tabel, dipasang manual agar tabel bisa dibuat read-only */
    private DefaultTableModel modelEvent;
 
    /** Format tanggal untuk validasi input & tampilan tabel (yyyy-MM-dd) */
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
 
    /**
     * Creates new form LaporanPenjualanFormFrame
     */
    public EventBazarFormFrame() {
        initComponents();
        initCustomComponents(); // <-- tambahan: setup tabel, load data, dll
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnPesanan = new javax.swing.JButton();
        btnPorduk = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnPengguna = new javax.swing.JButton();
        btnVerifikasi = new javax.swing.JButton();
        btnEvent = new javax.swing.JButton();
        btnTracking = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNamaEvent = new javax.swing.JTextField();
        tfIdEvent = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventBazar = new javax.swing.JTable();
        btnTambah = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfLokasi = new javax.swing.JTextField();
        tfTanggalEvent = new javax.swing.JTextField();
        btnEdit = new javax.swing.JToggleButton();
        btnHapus = new javax.swing.JToggleButton();
        btnReset = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(11, 45, 107));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Terra Snack");

        btnDashboard.setBackground(new java.awt.Color(11, 45, 107));
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dahboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        btnPesanan.setBackground(new java.awt.Color(11, 45, 107));
        btnPesanan.setForeground(new java.awt.Color(255, 255, 255));
        btnPesanan.setText("Pesanan");
        btnPesanan.addActionListener(this::btnPesananActionPerformed);

        btnPorduk.setBackground(new java.awt.Color(11, 45, 107));
        btnPorduk.setForeground(new java.awt.Color(255, 255, 255));
        btnPorduk.setText("Produk");
        btnPorduk.addActionListener(this::btnPordukActionPerformed);

        btnLaporan.setBackground(new java.awt.Color(11, 45, 107));
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setText("Laporan");
        btnLaporan.addActionListener(this::btnLaporanActionPerformed);

        btnPengguna.setBackground(new java.awt.Color(11, 45, 107));
        btnPengguna.setForeground(new java.awt.Color(255, 255, 255));
        btnPengguna.setText("Pengguna");
        btnPengguna.addActionListener(this::btnPenggunaActionPerformed);

        btnVerifikasi.setBackground(new java.awt.Color(11, 45, 107));
        btnVerifikasi.setForeground(new java.awt.Color(255, 255, 255));
        btnVerifikasi.setText("Verifikasi");
        btnVerifikasi.addActionListener(this::btnVerifikasiActionPerformed);

        btnEvent.setBackground(new java.awt.Color(11, 45, 107));
        btnEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnEvent.setText("Event");
        btnEvent.addActionListener(this::btnEventActionPerformed);

        btnTracking.setBackground(new java.awt.Color(11, 45, 107));
        btnTracking.setForeground(new java.awt.Color(255, 255, 255));
        btnTracking.setText("Tracking");
        btnTracking.addActionListener(this::btnTrackingActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPorduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTracking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerifikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(btnDashboard)
                .addGap(29, 29, 29)
                .addComponent(btnPesanan)
                .addGap(27, 27, 27)
                .addComponent(btnPorduk)
                .addGap(28, 28, 28)
                .addComponent(btnLaporan)
                .addGap(27, 27, 27)
                .addComponent(btnPengguna)
                .addGap(27, 27, 27)
                .addComponent(btnVerifikasi)
                .addGap(28, 28, 28)
                .addComponent(btnEvent)
                .addGap(26, 26, 26)
                .addComponent(btnTracking)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("EVENT BAZAR FORM");
        jLabel1.setAlignmentY(0.0F);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id Event           :");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Event    :");

        tfIdEvent.addActionListener(this::tfIdEventActionPerformed);

        tblEventBazar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID EVENT", "NAMA EVENT", "LOKASI", "TANGGAL EVENT"
            }
        ));
        jScrollPane1.setViewportView(tblEventBazar);

        btnTambah.setBackground(new java.awt.Color(51, 153, 0));
        btnTambah.setForeground(new java.awt.Color(0, 0, 0));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Lokasi              :");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tanggal Event :");

        btnEdit.setBackground(new java.awt.Color(255, 153, 0));
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setForeground(new java.awt.Color(0, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setBackground(new java.awt.Color(102, 102, 102));
        btnReset.setForeground(new java.awt.Color(0, 0, 0));
        btnReset.setText("Reset");
        btnReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset.addActionListener(this::btnResetActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNamaEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfIdEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTanggalEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNamaEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTanggalEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() {
        dateFormat.setLenient(false); // tolak tanggal yang "dipaksakan" valid
 
        setupTable();
        loadTableData();
 
        // Klik baris tabel -> auto-isi field (memudahkan Edit/Hapus)
        tblEventBazar.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (e.getValueIsAdjusting()) {
                return;
            }
            int selectedRow = tblEventBazar.getSelectedRow();
            if (selectedRow >= 0 && selectedRow < modelEvent.getRowCount()) {
                tfIdEvent.setText(String.valueOf(modelEvent.getValueAt(selectedRow, 0)));
                tfNamaEvent.setText(String.valueOf(modelEvent.getValueAt(selectedRow, 1)));
                tfLokasi.setText(String.valueOf(modelEvent.getValueAt(selectedRow, 2)));
                tfTanggalEvent.setText(String.valueOf(modelEvent.getValueAt(selectedRow, 3)));
            }
        });
 
        setLocationRelativeTo(null); // tampilkan form di tengah layar
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
 
    /**
     * Mengganti model tabel bawaan GUI Builder dengan DefaultTableModel
     * custom yang seluruh selnya tidak bisa diedit user.
     */
    private void setupTable() {
 
        String[] kolom = {"ID EVENT", "NAMA EVENT", "LOKASI", "TANGGAL EVENT"};
 
        modelEvent = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // semua kolom read-only
            }
        };
 
        tblEventBazar.setModel(modelEvent);
    }
 
    /**
     * Ambil seluruh data event_bazar dari database lewat EventBazarDAO,
     * lalu tampilkan ke tblEventBazar.
     */
    private void loadTableData() {
 
        modelEvent.setRowCount(0); // bersihkan isi tabel sebelum diisi ulang
 
        List<EventBazar> daftarEvent = eventBazarDAO.getAllEvent();
 
        for (EventBazar event : daftarEvent) {
            modelEvent.addRow(new Object[]{
                event.getIdEvent(),
                event.getNamaEvent(),
                event.getLokasi(),
                dateFormat.format(event.getTanggalMulai())
            });
        }
    }
 
    /**
     * Kosongkan semua field input.
     */
    private void clearFields() {
        tfIdEvent.setText("");
        tfNamaEvent.setText("");
        tfLokasi.setText("");
        tfTanggalEvent.setText("");
    }
 
    /**
     * Validasi field Nama Event, Lokasi, dan Tanggal Event (dipakai
     * bersama oleh Tambah & Edit). Mengembalikan tanggal hasil parsing,
     * atau null kalau validasi gagal (pesan error sudah ditampilkan).
     */
    private Date validasiDanParseTanggal() {
 
        String namaEvent = tfNamaEvent.getText().trim();
        String lokasi = tfLokasi.getText().trim();
        String tanggalStr = tfTanggalEvent.getText().trim();
 
        if (namaEvent.isEmpty() || lokasi.isEmpty() || tanggalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Nama Event, Lokasi, dan Tanggal Event tidak boleh kosong!",
                    "Input Tidak Valid",
                    JOptionPane.WARNING_MESSAGE);
            return null;
        }
 
        try {
            return dateFormat.parse(tanggalStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this,
                    "Format Tanggal Event salah! Gunakan format: yyyy-MM-dd\nContoh: 2026-06-18",
                    "Format Tanggal Salah",
                    JOptionPane.WARNING_MESSAGE);
            return null;
        }
    }
 
    /**
     * Tambah event bazar baru ke database.
     */
    private void tambahEvent() {
 
        Date tanggalEvent = validasiDanParseTanggal();
        if (tanggalEvent == null) {
            return; // pesan error sudah ditampilkan di validasiDanParseTanggal()
        }
 
        EventBazar event = new EventBazar();
        event.setNamaEvent(tfNamaEvent.getText().trim());
        event.setLokasi(tfLokasi.getText().trim());
        event.setTanggalMulai(tanggalEvent);
 
        boolean berhasil = eventBazarDAO.insert(event);
 
        if (berhasil) {
            JOptionPane.showMessageDialog(this,
                    "Event bazar berhasil ditambahkan!",
                    "Berhasil",
                    JOptionPane.INFORMATION_MESSAGE);
            loadTableData();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Gagal menambahkan event bazar. Periksa koneksi database Anda.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
 
    /**
     * Update event bazar yang sudah ada (berdasarkan Id Event yang diisi).
     */
    private void editEvent() {
 
        String idStr = tfIdEvent.getText().trim();
 
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Pilih dulu data yang ingin diedit (klik baris tabel, atau ketik Id Event lalu Enter).",
                    "Input Tidak Valid",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        int idEvent;
        try {
            idEvent = Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Id Event harus berupa angka!",
                    "Input Tidak Valid",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Date tanggalEvent = validasiDanParseTanggal();
        if (tanggalEvent == null) {
            return;
        }
 
        EventBazar event = new EventBazar();
        event.setIdEvent(idEvent);
        event.setNamaEvent(tfNamaEvent.getText().trim());
        event.setLokasi(tfLokasi.getText().trim());
        event.setTanggalMulai(tanggalEvent);
 
        boolean berhasil = eventBazarDAO.update(event);
 
        if (berhasil) {
            JOptionPane.showMessageDialog(this,
                    "Event bazar berhasil diupdate!",
                    "Berhasil",
                    JOptionPane.INFORMATION_MESSAGE);
            loadTableData();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Gagal mengupdate event bazar. Pastikan Id Event tersebut ada.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
 
    /**
     * Hapus event bazar berdasarkan Id Event yang diisi, dengan konfirmasi
     * terlebih dahulu.
     */
    private void hapusEvent() {
 
        String idStr = tfIdEvent.getText().trim();
 
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Pilih dulu data yang ingin dihapus (klik baris tabel, atau ketik Id Event lalu Enter).",
                    "Input Tidak Valid",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        int idEvent;
        try {
            idEvent = Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Id Event harus berupa angka!",
                    "Input Tidak Valid",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus event dengan Id " + idEvent + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
 
        if (konfirmasi != JOptionPane.YES_OPTION) {
            return; // user membatalkan
        }
 
        boolean berhasil = eventBazarDAO.delete(idEvent);
 
        if (berhasil) {
            JOptionPane.showMessageDialog(this,
                    "Event bazar berhasil dihapus!",
                    "Berhasil",
                    JOptionPane.INFORMATION_MESSAGE);
            loadTableData();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Gagal menghapus event bazar. Pastikan Id Event tersebut ada.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
 
    /**
     * Cari event berdasarkan Id Event (dipanggil saat user menekan Enter
     * di field tfIdEvent), lalu auto-isi field lainnya untuk Edit/Hapus.
     */
    private void cariEventById() {
 
        String idStr = tfIdEvent.getText().trim();
 
        if (idStr.isEmpty()) {
            return;
        }
 
        int idEvent;
        try {
            idEvent = Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Id Event harus berupa angka!",
                    "Input Tidak Valid",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        EventBazar event = eventBazarDAO.getEventById(idEvent);
 
        if (event == null) {
            JOptionPane.showMessageDialog(this,
                    "Event dengan Id " + idEvent + " tidak ditemukan.",
                    "Data Tidak Ditemukan",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
 
        tfNamaEvent.setText(event.getNamaEvent());
        tfLokasi.setText(event.getLokasi());
        tfTanggalEvent.setText(dateFormat.format(event.getTanggalMulai()));
    }
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        tambahEvent();
        btnTambah.setSelected(false); 
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tfIdEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdEventActionPerformed
        // TODO add your handling code here:
        cariEventById();
    }//GEN-LAST:event_tfIdEventActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        editEvent();
        btnEdit.setSelected(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        hapusEvent();
        btnHapus.setSelected(false);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clearFields();
        btnReset.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose(); // Tutup form Tracking saat ini untuk membebaskan memori
            new DashboardAdmin().setVisible(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka Dashboard: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesananActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose();
            new PesananForm().setVisible(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka Pesanan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPesananActionPerformed

    private void btnPordukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPordukActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose();
            new ProdukForm().setVisible(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka Produk: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPordukActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose();
            new LaporanPenjualanFormFrame().setVisible(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka Laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenggunaActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose();
            new PelangganForm().setVisible(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka Pengguna: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPenggunaActionPerformed

    private void btnVerifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifikasiActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose();
            new FormUploadPembayaran().setVisible(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka Event: " + e.getMessage());
        }
    }//GEN-LAST:event_btnVerifikasiActionPerformed

    private void btnEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEventActionPerformed

    private void btnTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackingActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose();
            new TrackingPesananForm().setVisible(true);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka Tracking: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTrackingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EventBazarFormFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JToggleButton btnEdit;
    private javax.swing.JButton btnEvent;
    private javax.swing.JToggleButton btnHapus;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnPengguna;
    private javax.swing.JButton btnPesanan;
    private javax.swing.JButton btnPorduk;
    private javax.swing.JToggleButton btnReset;
    private javax.swing.JToggleButton btnTambah;
    private javax.swing.JButton btnTracking;
    private javax.swing.JButton btnVerifikasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEventBazar;
    private javax.swing.JTextField tfIdEvent;
    private javax.swing.JTextField tfLokasi;
    private javax.swing.JTextField tfNamaEvent;
    private javax.swing.JTextField tfTanggalEvent;
    // End of variables declaration//GEN-END:variables
}