/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.terra_snack.view;

import com.mycompany.terra_snack.database.DatabaseConnection;
import com.mycompany.terra_snack.model.Pelanggan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LOQ
 */
public class PelangganForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PelangganForm.class.getName());
    private DefaultTableModel tableModel;
    private List<Pelanggan> daftarPelanggan;
    private Pelanggan pelangganSelected;

    /**
     * Creates new form PelangganForm
     */
    public PelangganForm() {
        initComponents();
        daftarPelanggan = new ArrayList<>();
        setupTable();
        loadPelangganData();
        setupForm();
    }

     private void setupTable() {
        tableModel = (DefaultTableModel) JTPelanggan.getModel();
        
        // Allow multiple row selection
        JTPelanggan.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        JTPelanggan.setRowSelectionAllowed(true);
    }

    private void setupForm() {
        // ID Pelanggan should be read-only (auto-generated)
        Jpelanggan.setEditable(false);
        Jpelanggan.setBackground(new java.awt.Color(240, 240, 240));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JNPelanggan = new javax.swing.JTextField();
        JEmail = new javax.swing.JTextField();
        JNoHP = new javax.swing.JTextField();
        JAlamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Jpelanggan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTPelanggan = new javax.swing.JTable();
        Jtambah = new javax.swing.JButton();
        JUpdate = new javax.swing.JButton();
        JHapus = new javax.swing.JButton();
        JRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nama Pelanggan :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Email   :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NO HP  :");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Alamat :");

        JNPelanggan.addActionListener(this::JNPelangganActionPerformed);

        JNoHP.addActionListener(this::JNoHPActionPerformed);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID Pelanggan :");

        Jpelanggan.addActionListener(this::JpelangganActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JNPelanggan)
                    .addComponent(JEmail)
                    .addComponent(JNoHP)
                    .addComponent(JAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(Jpelanggan))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Jpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JNPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(JAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        JTPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID Pelanggan", "Nama", "Email", "NO HP", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTPelanggan);

        Jtambah.setBackground(new java.awt.Color(0, 204, 51));
        Jtambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jtambah.setForeground(new java.awt.Color(255, 255, 255));
        Jtambah.setText("Tambah Pelanggan");
        Jtambah.addActionListener(this::JtambahActionPerformed);

        JUpdate.setBackground(new java.awt.Color(0, 204, 255));
        JUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JUpdate.setForeground(new java.awt.Color(255, 255, 255));
        JUpdate.setText("Update Data");
        JUpdate.addActionListener(this::JUpdateActionPerformed);

        JHapus.setBackground(new java.awt.Color(255, 51, 51));
        JHapus.setForeground(new java.awt.Color(255, 255, 255));
        JHapus.setText("Hapus Pelanggan");
        JHapus.addActionListener(this::JHapusActionPerformed);

        JRefresh.setBackground(new java.awt.Color(204, 204, 204));
        JRefresh.setForeground(new java.awt.Color(255, 255, 255));
        JRefresh.setText("Refresh");
        JRefresh.addActionListener(this::JRefreshActionPerformed);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Terra Snack - Pelanggan Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jtambah)
                                .addGap(18, 18, 18)
                                .addComponent(JUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(JHapus)
                                .addGap(18, 18, 18)
                                .addComponent(JRefresh))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel6)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtambah)
                    .addComponent(JUpdate)
                    .addComponent(JHapus)
                    .addComponent(JRefresh))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JNoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNoHPActionPerformed

    private void JtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtambahActionPerformed
        tambahPelanggan();
    }//GEN-LAST:event_JtambahActionPerformed

    private void JUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUpdateActionPerformed
        updatePelanggan();
    }//GEN-LAST:event_JUpdateActionPerformed

    private void JNPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNPelangganActionPerformed

    private void JHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JHapusActionPerformed
        hapusPelanggan();

    }//GEN-LAST:event_JHapusActionPerformed

    private void JRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRefreshActionPerformed
        loadPelangganData();
        clearForm();
    }//GEN-LAST:event_JRefreshActionPerformed

    private void JpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpelangganActionPerformed

        private void loadPelangganData() {
            // Clear table
            tableModel.setRowCount(0);
            daftarPelanggan.clear();

            String sql = "SELECT * FROM pelanggan ORDER BY pelanggan_id ASC";

            try (Connection conn = DatabaseConnection.getConnection(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {

                int no = 1;
                while (rs.next()) {
                    Pelanggan p = new Pelanggan();
                    p.setPelangganId(rs.getInt("pelanggan_id"));
                    p.setNama(rs.getString("nama"));
                    p.setAlamat(rs.getString("alamat"));
                    p.setNoHp(rs.getString("no_hp"));

                    // Handle email if column exists
                    String email = "";
                    try {
                        email = rs.getString("email");
                    } catch (SQLException e) {
                        email = "-";
                    }

                    daftarPelanggan.add(p);

                    Object[] row = {
                        no++,
                        "PLG-" + String.format("%04d", p.getPelangganId()),
                        p.getNama(),
                        email != null ? email : "-",
                        p.getNoHp(),
                        p.getAlamat()
                    };
                    tableModel.addRow(row);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,
                        "Error loading data: " + e.getMessage(),
                        "Database Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }

        /**
         * Load data ke form berdasarkan row yang dipilih
         */
        private void loadSelectedDataFromRow() {
            int[] selectedRows = JTPelanggan.getSelectedRows();

            // Jika hanya 1 baris yang dipilih, load ke form
            if (selectedRows.length == 1) {
                int row = selectedRows[0];
                String idPelangganStr = tableModel.getValueAt(row, 1).toString();
                int pelangganId = Integer.parseInt(idPelangganStr.replace("PLG-", ""));

                for (Pelanggan p : daftarPelanggan) {
                    if (p.getPelangganId() == pelangganId) {
                        Jpelanggan.setText("PLG-" + String.format("%04d", p.getPelangganId()));
                        JNPelanggan.setText(p.getNama());
                        JNoHP.setText(p.getNoHp());
                        JAlamat.setText(p.getAlamat());

                        // Load email
                        String email = tableModel.getValueAt(row, 3).toString();
                        JEmail.setText(email.equals("-") ? "" : email);
                        break;
                    }
                }
            } else if (selectedRows.length > 1) {
                // Jika lebih dari 1, kosongkan form (karena akan digunakan untuk hapus massal)
                Jpelanggan.setText("");
                JNPelanggan.setText("");
                JEmail.setText("");
                JNoHP.setText("");
                JAlamat.setText("");
            }
        }
        
         private void tambahPelanggan() {
        // Pastikan tidak ada row yang dipilih saat menambah
        if (JTPelanggan.getSelectedRowCount() > 0) {
            JOptionPane.showMessageDialog(this,
                "Batal pilih data terlebih dahulu sebelum menambah data baru!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String nama = JNPelanggan.getText().trim();
        String email = JEmail.getText().trim();
        String noHp = JNoHP.getText().trim();
        String alamat = JAlamat.getText().trim();

        // Validasi
        if (nama.isEmpty() || noHp.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Nama, No. HP, dan Alamat harus diisi!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!noHp.matches("08[0-9]{8,11}")) {
            JOptionPane.showMessageDialog(this,
                "Nomor HP harus dimulai dengan 08 dan 10-13 digit!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "INSERT INTO pelanggan (nama, email, no_hp, alamat) VALUES (?, ?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, nama);
            ps.setString(2, email.isEmpty() ? null : email);
            ps.setString(3, noHp);
            ps.setString(4, alamat);

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this,
                    "Pelanggan berhasil ditambahkan!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                loadPelangganData();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menambahkan pelanggan!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

         private void updatePelanggan() {
        int[] selectedRows = JTPelanggan.getSelectedRows();
        
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this,
                "Pilih 1 pelanggan yang akan diupdate dengan klik pada baris tabel!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedRows.length > 1) {
            JOptionPane.showMessageDialog(this,
                "Update hanya bisa dilakukan untuk 1 pelanggan.\n" +
                "Anda memilih " + selectedRows.length + " pelanggan.\n\n" +
                "Silakan pilih hanya 1 baris.",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nama = JNPelanggan.getText().trim();
        String email = JEmail.getText().trim();
        String noHp = JNoHP.getText().trim();
        String alamat = JAlamat.getText().trim();

        // Validasi
        if (nama.isEmpty() || noHp.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Nama, No. HP, dan Alamat harus diisi!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!noHp.matches("08[0-9]{8,11}")) {
            JOptionPane.showMessageDialog(this,
                "Nomor HP harus dimulai dengan 08 dan 10-13 digit!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
             int row = selectedRows[0];
        String idPelangganStr = tableModel.getValueAt(row, 1).toString();
        int pelangganId = Integer.parseInt(idPelangganStr.replace("PLG-", ""));

        int confirm = JOptionPane.showConfirmDialog(this,
            "Update data pelanggan " + idPelangganStr + "?",
            "Konfirmasi Update",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            String sql = "UPDATE pelanggan SET nama = ?, email = ?, no_hp = ?, alamat = ? WHERE pelanggan_id = ?";

            try (Connection conn = DatabaseConnection.getConnection();
                 PreparedStatement ps = conn.prepareStatement(sql)) {

                ps.setString(1, nama);
                ps.setString(2, email.isEmpty() ? null : email);
                ps.setString(3, noHp);
                ps.setString(4, alamat);
                ps.setInt(5, pelangganId);

                int rowsAffected = ps.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this,
                        "Data pelanggan berhasil diupdate!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                    loadPelangganData();
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Gagal mengupdate data pelanggan!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

          private void hapusPelanggan() {
        int[] selectedRows = JTPelanggan.getSelectedRows();
        
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this,
                "Pilih pelanggan yang akan dihapus dengan klik pada baris tabel!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus " + selectedRows.length + " pelanggan terpilih?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            int successCount = 0;
            int failCount = 0;
            
            String sql = "DELETE FROM pelanggan WHERE pelanggan_id = ?";

            try (Connection conn = DatabaseConnection.getConnection();
                 PreparedStatement ps = conn.prepareStatement(sql)) {

                for (int row : selectedRows) {
                    String idPelangganStr = tableModel.getValueAt(row, 1).toString();
                    int pelangganId = Integer.parseInt(idPelangganStr.replace("PLG-", ""));
                    
                    ps.setInt(1, pelangganId);
                    int rowsAffected = ps.executeUpdate();
                    
                    if (rowsAffected > 0) {
                        successCount++;
                    } else {
                        failCount++;
                    }
                }

                String message = "Berhasil menghapus " + successCount + " pelanggan.";
                if (failCount > 0) {
                    message += "\nGagal menghapus " + failCount + " pelanggan.";
                }
                
                JOptionPane.showMessageDialog(this,
                    message,
                    "Hasil Hapus",
                    JOptionPane.INFORMATION_MESSAGE);
                
                loadPelangganData();
                clearForm();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

         private void clearForm() {
        Jpelanggan.setText("");
        JNPelanggan.setText("");
        JEmail.setText("");
        JNoHP.setText("");
        JAlamat.setText("");
        
        // Clear selection
        JTPelanggan.clearSelection();
    }

        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> new PelangganForm().setVisible(true));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JAlamat;
    private javax.swing.JTextField JEmail;
    private javax.swing.JButton JHapus;
    private javax.swing.JTextField JNPelanggan;
    private javax.swing.JTextField JNoHP;
    private javax.swing.JButton JRefresh;
    private javax.swing.JTable JTPelanggan;
    private javax.swing.JButton JUpdate;
    private javax.swing.JTextField Jpelanggan;
    private javax.swing.JButton Jtambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

  
    

}
