/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.terra_snack.view;

import com.mycompany.terra_snack.database.DatabaseConnection;
import com.mycompany.terra_snack.model.Pesanan;
import com.mycompany.terra_snack.services.OrderService;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LOQ
 */
public class PesananForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PesananForm.class.getName());
    private DefaultTableModel tableModel;
    private List<Pesanan> daftarPesanan;
    private OrderService orderService;
    private Pesanan pesananSelected;

    /**
     * Creates new form PesananForm
     */
    public PesananForm() {
        initComponents();
        daftarPesanan = new ArrayList<>();
        orderService = new OrderService();
        setupTable();
        loadPesananData();
    }

    private void setupTable() {
        tableModel = (DefaultTableModel) JPesanan.getModel();
        JPesanan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JPesanan.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && JPesanan.getSelectedRow() != -1) {
                loadSelectedData();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPelanggan = new javax.swing.JTextField();
        JCatatan = new javax.swing.JTextField();
        JHarga = new javax.swing.JTextField();
        CPesanan = new javax.swing.JComboBox<>();
        CPengambilan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JPesanan = new javax.swing.JTable();
        JUpdate = new javax.swing.JButton();
        JTambah = new javax.swing.JButton();
        JHapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nama Pelanggan :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tipe Pesanan :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Catatan :");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Harga :");

        JPelanggan.addActionListener(this::JPelangganActionPerformed);

        JCatatan.addActionListener(this::JCatatanActionPerformed);

        JHarga.setEditable(false);

        CPesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Pesanan", "Event", "Pre Order", " ", " " }));
        CPesanan.setToolTipText("");

        CPengambilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metode", "Pickup", "Delivery" }));
        CPengambilan.addActionListener(this::CPengambilanActionPerformed);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Pengambilan :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPelanggan)
                    .addComponent(JCatatan)
                    .addComponent(JHarga)
                    .addComponent(CPesanan, 0, 151, Short.MAX_VALUE)
                    .addComponent(CPengambilan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(746, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        JPesanan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        JPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "ID Pesanan", "Kode Pesanan", "ID Pelanggan", "Jenis Pesanan", "Tanggal Pesanan", "Status Pelaksanaan Pesanan", "Catatan", "Total Harga", "Status Pesanan", "Detail Pesanan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JPesanan);

        JUpdate.setBackground(new java.awt.Color(37, 99, 235));
        JUpdate.setForeground(new java.awt.Color(255, 255, 255));
        JUpdate.setText("Update Status");
        JUpdate.addActionListener(this::JUpdateActionPerformed);

        JTambah.setBackground(new java.awt.Color(51, 204, 0));
        JTambah.setForeground(new java.awt.Color(255, 255, 255));
        JTambah.setText("Tambah Pesanan");
        JTambah.setToolTipText("");
        JTambah.addActionListener(this::JTambahActionPerformed);

        JHapus.setBackground(new java.awt.Color(255, 51, 51));
        JHapus.setForeground(new java.awt.Color(255, 255, 255));
        JHapus.setText("Hapus Pesanan");
        JHapus.addActionListener(this::JHapusActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Form Data Pesanan");

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(JTambah)
                        .addGap(105, 105, 105)
                        .addComponent(JUpdate)
                        .addGap(127, 127, 127)
                        .addComponent(JHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JUpdate)
                    .addComponent(JTambah)
                    .addComponent(JHapus))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPelangganActionPerformed

    private void JCatatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCatatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCatatanActionPerformed

    private void CPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPengambilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPengambilanActionPerformed

    private void JHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JHapusActionPerformed
        hapusPesanan();
    }//GEN-LAST:event_JHapusActionPerformed

    private void JUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUpdateActionPerformed
        updateStatusPesanan();
    }//GEN-LAST:event_JUpdateActionPerformed

    private void JTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTambahActionPerformed
        tambahPesanan();
    }//GEN-LAST:event_JTambahActionPerformed

    private void loadPesananData() {
        // Clear table
        tableModel.setRowCount(0);
        daftarPesanan.clear();

        String sql = "SELECT * FROM pesanan ORDER BY pesanan_id ASC";

        try (Connection conn = DatabaseConnection.getConnection(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {

            int no = 1;
            while (rs.next()) {
                Pesanan p = new Pesanan();
                p.setPesananId(rs.getInt("pesanan_id"));
                p.setPelangganId(rs.getInt("pelanggan_id"));
                p.setTanggalPesanan(rs.getTimestamp("tanggal_pesanan"));

                // Get additional fields from database
                String kodePesanan = rs.getString("kode_pesanan");
                String jenisPesanan = rs.getString("jenis_pesanan");
                String modeFulfillment = rs.getString("metode_fulfillment");
                String catatan = rs.getString("catatan");
                double totalHarga = rs.getDouble("total_harga");
                String statusPesanan = rs.getString("status_pesanan");

                daftarPesanan.add(p);

                Object[] row = {
                    no++,
                    p.getPesananId(),
                    kodePesanan != null ? kodePesanan : "-",
                    p.getPelangganId(),
                    jenisPesanan != null ? jenisPesanan : "-",
                    p.getTanggalPesanan(),
                    modeFulfillment != null ? modeFulfillment : "-",
                    catatan != null ? catatan : "-",
                    totalHarga,
                    p.getStatusPesanan() != null ? p.getStatusPesanan() : "MENUNGGU_PEMBAYARAN",
                    "-"
                };
                tableModel.addRow(row);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error loading data: " + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void loadSelectedData() {
        int selectedRow = JPesanan.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        int pesananId = (int) tableModel.getValueAt(selectedRow, 1);

        for (Pesanan p : daftarPesanan) {
            if (p.getPesananId() == pesananId) {
                pesananSelected = p;

                // Load data ke form (untuk ID Pelanggan)
                JPelanggan.setText(String.valueOf(p.getPelangganId()));
                JCatatan.setText(tableModel.getValueAt(selectedRow, 7).toString());

                // Set combo boxes
                String jenisPesanan = tableModel.getValueAt(selectedRow, 4).toString();
                CPesanan.setSelectedItem(jenisPesanan);

                String modeFulfillment = tableModel.getValueAt(selectedRow, 6).toString();
                CPengambilan.setSelectedItem(modeFulfillment);

                // Set harga
                double harga = (double) tableModel.getValueAt(selectedRow, 8);
                JHarga.setText(String.valueOf(harga));

                break;
            }
        }
    }

    private void tambahPesanan() {
        // Validasi input
        if (JPelanggan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "ID Pelanggan harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int pelangganId;
        try {
            pelangganId = Integer.parseInt(JPelanggan.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "ID Pelanggan harus berupa angka!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (pelangganId <= 0) {
            JOptionPane.showMessageDialog(this,
                    "ID Pelanggan tidak valid!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Generate kode pesanan otomatis
        String kodePesanan = generateKodePesanan();
        String jenisPesanan = CPesanan.getSelectedItem().toString();
        String modeFulfillment = CPengambilan.getSelectedItem().toString();
        String catatan = JCatatan.getText().trim();

        double totalHarga = 0;
        try {
            if (!JHarga.getText().trim().isEmpty()) {
                totalHarga = Double.parseDouble(JHarga.getText().trim());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Harga harus berupa angka!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "INSERT INTO pesanan (kode_pesanan, pelanggan_id, jenis_pesanan, tanggal_pesanan, metode_fulfillment, catatan, total_harga, status_pesanan) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, kodePesanan);
            ps.setInt(2, pelangganId);
            ps.setString(3, jenisPesanan.equals("Jenis Pesanan") ? null : jenisPesanan);
            ps.setTimestamp(4, Timestamp.valueOf(LocalDateTime.now()));
            ps.setString(5, modeFulfillment.equals("Metode") ? null : modeFulfillment);
            ps.setString(6, catatan.isEmpty() ? null : catatan);
            ps.setDouble(7, totalHarga);
            ps.setString(8, "MENUNGGU_PEMBAYARAN");

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this,
                        "Pesanan berhasil ditambahkan!\nKode Pesanan: " + kodePesanan,
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                loadPesananData();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Gagal menambahkan pesanan!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void updateStatusPesanan() {
        if (pesananSelected == null) {
            JOptionPane.showMessageDialog(this,
                    "Pilih pesanan yang akan diupdate dari tabel!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String[] statuses = {"MENUNGGU_PEMBAYARAN", "MENUNGGU_VERIFIKASI", "DIPROSES", "SIAP", "SELESAI", "DITOLAK"};
        String currentStatus = tableModel.getValueAt(JPesanan.getSelectedRow(), 9).toString();

        String selectedStatus = (String) JOptionPane.showInputDialog(
                this,
                "Pilih status baru untuk pesanan:",
                "Update Status Pesanan",
                JOptionPane.QUESTION_MESSAGE,
                null,
                statuses,
                currentStatus
        );

        if (selectedStatus != null && !selectedStatus.equals(currentStatus)) {
            String sql = "UPDATE pesanan SET status_pesanan = ? WHERE pesanan_id = ?";

            try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

                ps.setString(1, selectedStatus);
                ps.setInt(2, pesananSelected.getPesananId());

                int rowsAffected = ps.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Status pesanan berhasil diupdate menjadi: " + selectedStatus,
                            "Sukses",
                            JOptionPane.INFORMATION_MESSAGE);
                    loadPesananData();
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Gagal mengupdate status pesanan!",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,
                        "Error: " + e.getMessage(),
                        "Database Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

    private void hapusPesanan() {
        if (pesananSelected == null) {
            JOptionPane.showMessageDialog(this,
                    "Pilih pesanan yang akan dihapus dari tabel!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus pesanan ID: " + pesananSelected.getPesananId() + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            // Cek status pesanan
            String currentStatus = tableModel.getValueAt(JPesanan.getSelectedRow(), 9).toString();
            if (!currentStatus.equals("MENUNGGU_PEMBAYARAN")) {
                JOptionPane.showMessageDialog(this,
                        "Pesanan hanya bisa dihapus jika statusnya MENUNGGU_PEMBAYARAN.\n"
                        + "Status saat ini: " + currentStatus,
                        "Peringatan",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            String sql = "DELETE FROM pesanan WHERE pesanan_id = ?";

            try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

                ps.setInt(1, pesananSelected.getPesananId());

                int rowsAffected = ps.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Pesanan berhasil dihapus!",
                            "Sukses",
                            JOptionPane.INFORMATION_MESSAGE);
                    loadPesananData();
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Gagal menghapus pesanan!",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,
                        "Error: " + e.getMessage(),
                        "Database Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }
    
     private String generateKodePesanan() {
        // Generate kode pesanan format: TRX + timestamp
        return "TRX" + System.currentTimeMillis() % 1000000;
    }
    
    private void clearForm() {
        JPelanggan.setText("");
        JCatatan.setText("");
        JHarga.setText("");
        CPesanan.setSelectedIndex(0);
        CPengambilan.setSelectedIndex(0);
        pesananSelected = null;
        JPesanan.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PesananForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CPengambilan;
    private javax.swing.JComboBox<String> CPesanan;
    private javax.swing.JTextField JCatatan;
    private javax.swing.JButton JHapus;
    private javax.swing.JTextField JHarga;
    private javax.swing.JTextField JPelanggan;
    private javax.swing.JTable JPesanan;
    private javax.swing.JButton JTambah;
    private javax.swing.JButton JUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
