/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.terra_snack.view;

import com.mycompany.terra_snack.model.Produk;
import java.util.List;

/**
 *
 * @author YodhaAce
 */
public class ProdukForm extends javax.swing.JFrame {

    /**
     * Creates new form ProdukForm1
     */
    private com.mycompany.terra_snack.dao.ProdukDAO produkDAO = new com.mycompany.terra_snack.dao.ProdukDAO();
    private com.mycompany.terra_snack.dao.PromoDAO promoDAO = new com.mycompany.terra_snack.dao.PromoDAO();

    public ProdukForm() {
        initComponents();
        loadDataToTable();
        aturLebarKolomOtomatis(tblProduk);
        jPanel3.setBackground(new java.awt.Color(11, 45, 107));
        btnDashboard.setBackground(new java.awt.Color(37, 99, 235));
        btnDashboard.setForeground(java.awt.Color.WHITE);

    }

    private void loadDataToTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblProduk.getModel();
        model.setRowCount(0);

        List<com.mycompany.terra_snack.model.Produk> listProduk = produkDAO.getAllProduk();
        for (com.mycompany.terra_snack.model.Produk p : listProduk) {
            Object[] rowProduk = {
                p.getProdukId(),
                p.getNamaProduk(),
                p.getHarga(),
                p.getStok(),
                p.getMinimalOrder(),
                p.getStatusProduk()
            };
            model.addRow(rowProduk);

            List<com.mycompany.terra_snack.model.VarianProduk> listVarian = produkDAO.getVarianByProduk(p.getProdukId());
            for (com.mycompany.terra_snack.model.VarianProduk v : listVarian) {
                Object[] rowVarian = {
                    v.getVarianId(), // REVISI: Menampilkan ID asli Varian dari database
                    p.getNamaProduk() + " - " + v.getNamaVarian(),
                    p.getHarga(),
                    v.getStokVarian(),
                    p.getMinimalOrder(),
                    "Aktif"
                };
                model.addRow(rowVarian);
            }
        }

        aturLebarKolomOtomatis(tblProduk);
    }

    private void aturLebarKolomOtomatis(javax.swing.JTable table) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            int totalLebarKonten = 0;
            int[] lebarKolomArray = new int[table.getColumnCount()];

            for (int column = 0; column < table.getColumnCount(); column++) {
                int lebarKolom = 50;

                javax.swing.table.TableCellRenderer headerRenderer = table.getTableHeader().getDefaultRenderer();
                java.awt.Component headerComp = headerRenderer.getTableCellRendererComponent(table, table.getColumnName(column), false, false, 0, column);
                lebarKolom = Math.max(headerComp.getPreferredSize().width + 15, lebarKolom);

                for (int row = 0; row < table.getRowCount(); row++) {
                    javax.swing.table.TableCellRenderer renderer = table.getCellRenderer(row, column);
                    java.awt.Component comp = table.prepareRenderer(renderer, row, column);
                    lebarKolom = Math.max(comp.getPreferredSize().width + 15, lebarKolom);
                }
                lebarKolomArray[column] = lebarKolom;
                totalLebarKonten += lebarKolom;
            }

            int lebarViewport = table.getParent() != null ? table.getParent().getWidth() : 0;

            if (totalLebarKonten < lebarViewport) {

                table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            } else {

                table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            }

            for (int column = 0; column < table.getColumnCount(); column++) {
                table.getColumnModel().getColumn(column).setPreferredWidth(lebarKolomArray[column]);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        tfStok = new javax.swing.JTextField();
        tfMinOrder = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfVarian = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnSubPromo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Produk :");
        jLabel1.setToolTipText("");

        jLabel2.setText("Nama Produk :");

        jLabel3.setText("Harga:");

        jLabel4.setText("Stok :");

        jLabel5.setText("Minimal Order :");

        jLabel6.setText("Status : ");

        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        tfMinOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMinOrderActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jScrollPane1.setToolTipText("");

        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Produk", "Harga", "Stok", "Min Order", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduk);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Habis" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        jLabel7.setText("Cari Nama:");

        tfCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel9.setText("Nama Varian(Kalau ada) :");

        tfVarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVarianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfId)
                            .addComponent(tfStok)
                            .addComponent(tfMinOrder)
                            .addComponent(cbStatus, 0, 160, Short.MAX_VALUE)
                            .addComponent(tfVarian)
                            .addComponent(tfNama)
                            .addComponent(tfHarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCari)
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfVarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMinOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(8, 45, 91));
        jPanel3.setPreferredSize(new java.awt.Dimension(131, 0));

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnSubPromo.setText("Promo Diskon");
        btnSubPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubPromoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubPromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnDashboard)
                .addGap(18, 18, 18)
                .addComponent(btnSubPromo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadDataToTable();

        tfId.setText("");
        tfNama.setText("");
        tfVarian.setText("");
        tfHarga.setText("");
        tfStok.setText("");
        tfMinOrder.setText("");
        tfCari.setText("");
        cbStatus.setSelectedIndex(0);

        tfNama.setEditable(true);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tfMinOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMinOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMinOrderActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (tfNama.getText().isEmpty() || tfHarga.getText().isEmpty() || tfStok.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama Produk, Harga, dan Stok wajib diisi!");
            return;
        }

        String namaInput = tfNama.getText().trim();
        String varianInput = tfVarian.getText().trim();

        for (int i = 0; i < tblProduk.getRowCount(); i++) {
            String namaDiTabel = tblProduk.getValueAt(i, 1).toString();

            if (!varianInput.isEmpty()) {
                String formatGabung = namaInput + " - " + varianInput;
                if (namaDiTabel.equalsIgnoreCase(formatGabung)) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Error: Varian '" + varianInput + "' sudah ada di produk '" + namaInput + "'!",
                            "Data Duplikat", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                if (namaDiTabel.equalsIgnoreCase(namaInput)) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Error: Produk Utama '" + namaInput + "' sudah terdaftar!",
                            "Data Duplikat", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }

        if (!varianInput.isEmpty()) {

            int idInduk = -1;
            for (int i = 0; i < tblProduk.getRowCount(); i++) {
                String namaDiTabel = tblProduk.getValueAt(i, 1).toString();
                if (!namaDiTabel.contains(" - ") && namaDiTabel.equalsIgnoreCase(namaInput)) {
                    idInduk = Integer.parseInt(tblProduk.getValueAt(i, 0).toString());
                    break;
                }
            }

            if (idInduk == -1) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Error: Produk utama '" + namaInput + "' tidak ditemukan!\nSilahkan tambah produk utama terlebih dahulu.",
                        "Induk Tidak Ditemukan", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            com.mycompany.terra_snack.model.VarianProduk v = new com.mycompany.terra_snack.model.VarianProduk();
            v.setProdukId(idInduk);
            v.setNamaVarian(varianInput);
            v.setStokVarian(Integer.parseInt(tfStok.getText()));

            if (produkDAO.insertVarian(v)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Varian rasa baru berhasil ditambahkan!");
                btnRefreshActionPerformed(evt);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambahkan varian!");
            }
        } else {
            Produk p = new Produk();
            p.setNamaProduk(namaInput);
            p.setHarga(Double.parseDouble(tfHarga.getText()));
            p.setStok(Integer.parseInt(tfStok.getText()));
            p.setMinimalOrder(Integer.parseInt(tfMinOrder.getText()));
            p.setStatusProduk(cbStatus.getSelectedItem().toString());
            p.setGambarProduk("");

            if (produkDAO.insertProduk(p)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Produk utama berhasil ditambahkan!");
                btnRefreshActionPerformed(evt);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambahkan produk utama!");
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (tfId.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data dari tabel terlebih dahulu!");
            return;
        }

        int id = Integer.parseInt(tfId.getText());
        int row = tblProduk.getSelectedRow();
        String namaLengkapDiTabel = tblProduk.getValueAt(row, 1).toString();

        if (namaLengkapDiTabel.contains(" - ")) {
            com.mycompany.terra_snack.model.VarianProduk v = new com.mycompany.terra_snack.model.VarianProduk();
            v.setVarianId(id);
            v.setNamaVarian(tfVarian.getText().trim());
            v.setStokVarian(Integer.parseInt(tfStok.getText()));

            if (produkDAO.updateVarian(v)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Varian rasa berhasil diperbarui!");
                btnRefreshActionPerformed(evt);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data varian!");
            }
        } else {
            Produk p = new Produk();
            p.setProdukId(id);
            p.setNamaProduk(tfNama.getText().trim());
            p.setHarga(Double.parseDouble(tfHarga.getText()));
            p.setStok(Integer.parseInt(tfStok.getText()));
            p.setMinimalOrder(Integer.parseInt(tfMinOrder.getText()));
            p.setStatusProduk(cbStatus.getSelectedItem().toString());
            p.setGambarProduk("");

            if (produkDAO.updateProduk(p)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Produk utama berhasil diperbarui!");
                btnRefreshActionPerformed(evt);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data produk utama!");
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (tfId.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data dari tabel terlebih dahulu!");
            return;
        }

        int id = Integer.parseInt(tfId.getText());
        int row = tblProduk.getSelectedRow();
        String namaLengkapDiTabel = tblProduk.getValueAt(row, 1).toString();

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus data ini?", "Konfirmasi Hapus",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            if (namaLengkapDiTabel.contains(" - ")) {
                if (produkDAO.deleteVarian(id)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Varian rasa berhasil dihapus!");
                    btnRefreshActionPerformed(evt);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data varian!");
                }
            } else {
                if (produkDAO.deleteProduk(id)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Produk utama berhasil dihapus!");
                    btnRefreshActionPerformed(evt);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Gagal menghapus Produk Utama!\nPastikan semua varian rasa di bawah produk ini sudah dihapus terlebih dahulu.");
                }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblProduk.getModel();
        model.setRowCount(0);

        String keyword = tfCari.getText().trim();

        List<Produk> list = produkDAO.searchProduk(keyword);
        for (Produk p : list) {
            Object[] row = {
                p.getProdukId(),
                p.getNamaProduk(),
                p.getHarga(),
                p.getStok(),
                p.getMinimalOrder(),
                p.getStatusProduk()
            };
            model.addRow(row);

            List<com.mycompany.terra_snack.model.VarianProduk> listVarian = produkDAO.getVarianByProduk(p.getProdukId());
            for (com.mycompany.terra_snack.model.VarianProduk v : listVarian) {
                Object[] rowVarian = {
                    v.getVarianId(),
                    p.getNamaProduk() + " - " + v.getNamaVarian(),
                    p.getHarga(),
                    v.getStokVarian(),
                    p.getMinimalOrder(),
                    "Aktif"
                };
                model.addRow(rowVarian);
            }
        }

        aturLebarKolomOtomatis(tblProduk);
    }//GEN-LAST:event_btnCariActionPerformed

    private void tblProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdukMouseClicked

        int row = tblProduk.getSelectedRow();
        if (row != -1) {
            String idStr = tblProduk.getValueAt(row, 0).toString();
            String namaLengkap = tblProduk.getValueAt(row, 1).toString();
            String hargaStr = tblProduk.getValueAt(row, 2).toString();
            String stokStr = tblProduk.getValueAt(row, 3).toString();
            String minOrderStr = tblProduk.getValueAt(row, 4).toString();
            String statusStr = tblProduk.getValueAt(row, 5).toString();

            tfId.setText(idStr);
            tfHarga.setText(hargaStr);
            tfStok.setText(stokStr);
            tfMinOrder.setText(minOrderStr);
            cbStatus.setSelectedItem(statusStr);

            if (namaLengkap.contains(" - ")) {
                String[] pecahNama = namaLengkap.split(" - ");
                tfNama.setText(pecahNama[0]);
                tfVarian.setText(pecahNama[1]);
                tfNama.setEditable(false);
            } else {
                tfNama.setText(namaLengkap);
                tfVarian.setText("");
                tfNama.setEditable(true);
            }
        }
    }//GEN-LAST:event_tblProdukMouseClicked

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        DashboardAdmin dashboard = new DashboardAdmin();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnSubPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubPromoActionPerformed
        PromoForm form = new PromoForm();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSubPromoActionPerformed

    private void tfVarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVarianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdukForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubPromo;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduk;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfMinOrder;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfStok;
    private javax.swing.JTextField tfVarian;
    // End of variables declaration//GEN-END:variables
}
