/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.terra_snack.view;

import com.mycompany.terra_snack.model.Promo;
import java.util.List;

/**
 *
 * @author YodhaAce
 */
public class PromoForm extends javax.swing.JFrame {

    private com.mycompany.terra_snack.dao.PromoDAO promoDAO = new com.mycompany.terra_snack.dao.PromoDAO();

    /**
     * Creates new form PromoForm1
     */
    public PromoForm() {
        initComponents();
        loadDataToTable();
    }

    private void loadDataToTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPromo.getModel();
        model.setRowCount(0);
        List<Promo> list = promoDAO.getAllPromo();
        for (Promo pr : list) {
            Object[] row = {pr.getPromoId(), pr.getKodePromo(), pr.getNamaPromo(), pr.getJenisDiskon(), pr.getNilaiDiskon(), pr.getTanggalMulai(), pr.getTanggalSelesai(), pr.getStatus()};
            model.addRow(row);
        }
        aturLebarKolomOtomatis(tblPromo);
    }

    private void aturLebarKolomOtomatis(javax.swing.JTable table) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            int totalLebarKonten = 0;
            int[] lebarKolomArray = new int[table.getColumnCount()];

            for (int column = 0; column < table.getColumnCount(); column++) {
                int lebarKolom = 50;

                javax.swing.table.TableCellRenderer headerRenderer = table.getTableHeader().getDefaultRenderer();
                java.awt.Component headerComp = headerRenderer.getTableCellRendererComponent(table, table.getColumnName(column), false, false, 0, column);
                lebarKolom = Math.max(headerComp.getPreferredSize().width + 15, lebarKolom);

                for (int row = 0; row < table.getRowCount(); row++) {
                    javax.swing.table.TableCellRenderer renderer = table.getCellRenderer(row, column);
                    java.awt.Component comp = table.prepareRenderer(renderer, row, column);
                    lebarKolom = Math.max(comp.getPreferredSize().width + 15, lebarKolom);
                }
                lebarKolomArray[column] = lebarKolom;
                totalLebarKonten += lebarKolom;
            }

            int lebarViewport = table.getParent() != null ? table.getParent().getWidth() : 0;

            if (totalLebarKonten < lebarViewport) {
                table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            } else {
                table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            }

            for (int column = 0; column < table.getColumnCount(); column++) {
                table.getColumnModel().getColumn(column).setPreferredWidth(lebarKolomArray[column]);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbJenisDiskon = new javax.swing.JComboBox<>();
        cbStatusPromo = new javax.swing.JComboBox<>();
        tfIdPromo = new javax.swing.JTextField();
        tfKodePromo = new javax.swing.JTextField();
        tfNamaPromo = new javax.swing.JTextField();
        tfNilaiDiskon = new javax.swing.JTextField();
        tfTanggalMulai = new javax.swing.JTextField();
        tfTanggalSelesai = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPromo = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Promo");

        jLabel2.setText("Kode Promo");

        jLabel3.setText("Nama Promo");

        jLabel4.setText("Jenis Diskon");

        jLabel5.setText("Nilai Diskon");

        jLabel6.setText("Tanggal Mulai");

        jLabel7.setText("Tanggal Selesai");

        jLabel8.setText("Status Promo");

        cbJenisDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persen", "Normal" }));

        cbStatusPromo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Nonaktif" }));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tblPromo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode Promo", "Nama Promo", "Jenis", "Nilai", "Tgl Mulai", "Tgl Selesai", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPromoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPromo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTanggalSelesai)
                            .addComponent(tfTanggalMulai)
                            .addComponent(tfIdPromo)
                            .addComponent(tfKodePromo)
                            .addComponent(tfNamaPromo)
                            .addComponent(cbJenisDiskon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNilaiDiskon)
                            .addComponent(cbStatusPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfIdPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfKodePromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNamaPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbJenisDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNilaiDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTanggalSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbStatusPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(8, 45, 91));
        jPanel7.setPreferredSize(new java.awt.Dimension(131, 188));

        jButton6.setText("Produk Utama");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (tfKodePromo.getText().isEmpty() || tfNamaPromo.getText().isEmpty() || tfNilaiDiskon.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua inputan wajib diisi!");
            return;
        }

        Promo pr = new Promo();
        pr.setKodePromo(tfKodePromo.getText());
        pr.setNamaPromo(tfNamaPromo.getText());
        pr.setJenisDiskon(cbJenisDiskon.getSelectedItem().toString());
        pr.setNilaiDiskon(Double.parseDouble(tfNilaiDiskon.getText()));
        pr.setTanggalMulai(tfTanggalMulai.getText());
        pr.setTanggalSelesai(tfTanggalSelesai.getText());
        pr.setStatus(cbStatusPromo.getSelectedItem().toString());

        if (promoDAO.insertPromo(pr)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Promo berhasil ditambahkan!");
            loadDataToTable();
            tfIdPromo.setText("");
            tfKodePromo.setText("");
            tfNamaPromo.setText("");
            tfNilaiDiskon.setText("");
            tfTanggalMulai.setText("");
            tfTanggalSelesai.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambah promo!");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblPromoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromoMouseClicked
        int row = tblPromo.getSelectedRow();
        if (row != -1) {
            tfIdPromo.setText(tblPromo.getValueAt(row, 0).toString());
            tfKodePromo.setText(tblPromo.getValueAt(row, 1).toString());
            tfNamaPromo.setText(tblPromo.getValueAt(row, 2).toString());
            cbJenisDiskon.setSelectedItem(tblPromo.getValueAt(row, 3).toString());
            tfNilaiDiskon.setText(tblPromo.getValueAt(row, 4).toString());
            tfTanggalMulai.setText(tblPromo.getValueAt(row, 5).toString());
            tfTanggalSelesai.setText(tblPromo.getValueAt(row, 6).toString());
            cbStatusPromo.setSelectedItem(tblPromo.getValueAt(row, 7).toString());
        }
    }//GEN-LAST:event_tblPromoMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (tfIdPromo.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih promo dari tabel terlebih dahulu!");
            return;
        }
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus promo ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(tfIdPromo.getText());
            if (promoDAO.deletePromo(id)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Promo berhasil dihapus!");
                loadDataToTable();
                tfIdPromo.setText("");
                tfKodePromo.setText("");
                tfNamaPromo.setText("");
                tfNilaiDiskon.setText("");
                tfTanggalMulai.setText("");
                tfTanggalSelesai.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus promo!");
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadDataToTable();
        tfIdPromo.setText("");
        tfKodePromo.setText("");
        tfNamaPromo.setText("");
        tfNilaiDiskon.setText("");
        tfTanggalMulai.setText("");
        tfTanggalSelesai.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (tfIdPromo.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih promo dari tabel terlebih dahulu!");
            return;
        }

        Promo pr = new Promo();
        pr.setPromoId(Integer.parseInt(tfIdPromo.getText()));
        pr.setKodePromo(tfKodePromo.getText());
        pr.setNamaPromo(tfNamaPromo.getText());
        pr.setJenisDiskon(cbJenisDiskon.getSelectedItem().toString());
        pr.setNilaiDiskon(Double.parseDouble(tfNilaiDiskon.getText()));
        pr.setTanggalMulai(tfTanggalMulai.getText());
        pr.setTanggalSelesai(tfTanggalSelesai.getText());
        pr.setStatus(cbStatusPromo.getSelectedItem().toString());

        if (promoDAO.updatePromo(pr)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Promo berhasil diperbarui!");
            loadDataToTable();
            tfIdPromo.setText("");
            tfKodePromo.setText("");
            tfNamaPromo.setText("");
            tfNilaiDiskon.setText("");
            tfTanggalMulai.setText("");
            tfTanggalSelesai.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui promo!");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ProdukForm form = new ProdukForm();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbJenisDiskon;
    private javax.swing.JComboBox<String> cbStatusPromo;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPromo;
    private javax.swing.JTextField tfIdPromo;
    private javax.swing.JTextField tfKodePromo;
    private javax.swing.JTextField tfNamaPromo;
    private javax.swing.JTextField tfNilaiDiskon;
    private javax.swing.JTextField tfTanggalMulai;
    private javax.swing.JTextField tfTanggalSelesai;
    // End of variables declaration//GEN-END:variables
}
